### PR TITLE
Upstream info from previous filter

### PR DESCRIPTION
**Pull request by rahulanand16nov**
This PR now makes cache use of upstream info from the previous filter in the chain and passes the same into the MQ to be used by the singleton.

### CODE REVIEW

**Review by unleashed — COMMENTED** [review]
LGTM

**Review by NomadXD — CHANGES_REQUESTED** [review]
@rahulanand16nov You have modified the source files of the auth sub module here. If you need to change anything there , send a PR to its upstream. Don't make changes to that here since those won't be reflected in its upstream.

**Comment by rahulanand16nov** [comment]
> @rahulanand16nov You have modified the source files of the auth sub module here. If you need to change anything there , send a PR to its upstream. Don't make changes to that here since those won't be reflected in its upstream.

I just updated the submodule using `git pull` as it was pointing to an older commit.

**Review by NomadXD — APPROVED** [review]
Oh sorry didn't notice that. You can do remote update via  `--remote --merge` flags. Foreach approach also does the same thing. LGTM.

**Pull request merged**
